# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-sns_page_hook-extension}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Gay"]
  s.date = %q{2010-06-29}
  s.description = %q{Allows you to use page radius tags in stylesheets and javascripts from the SNS extension.}
  s.email = %q{jim@saturnflyer.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "config/locales/en.yml",
     "config/routes.rb",
     "cucumber.yml",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/tasks/sns_page_hook_extension_tasks.rake",
     "radiant-sns_page_hook-extension.gemspec",
     "sns_page_hook_extension.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/saturnflyer/radiant-sns_page_hook-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{SNS Page Hook Extension for Radiant CMS}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

